/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as ChoosePathRouteImport } from './routes/choose-path'
import { Route as ApplicationSubmittedRouteImport } from './routes/application-submitted'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkforceWorkersRouteImport } from './routes/workforce.workers'
import { Route as WorkforceRegisterRouteImport } from './routes/workforce.register'
import { Route as WorkforceProfileRouteImport } from './routes/workforce.profile'
import { Route as WorkforceDocumentsRouteImport } from './routes/workforce.documents'
import { Route as WorkforceDashboardRouteImport } from './routes/workforce.dashboard'
import { Route as WorkforceCategoriesRouteImport } from './routes/workforce.categories'
import { Route as WorkforceAssignmentsRouteImport } from './routes/workforce.assignments'
import { Route as MentorshipSessionsRouteImport } from './routes/mentorship.sessions'
import { Route as MentorshipRequestRouteImport } from './routes/mentorship.request'
import { Route as MentorshipProgramsRouteImport } from './routes/mentorship.programs'
import { Route as MentorshipProfileRouteImport } from './routes/mentorship.profile'
import { Route as MentorshipNotificationsRouteImport } from './routes/mentorship.notifications'
import { Route as MentorshipMessagesRouteImport } from './routes/mentorship.messages'
import { Route as MentorshipMentorsRouteImport } from './routes/mentorship.mentors'
import { Route as MentorshipDashboardRouteImport } from './routes/mentorship.dashboard'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as JobSeekerProfileRouteImport } from './routes/job-seeker.profile'
import { Route as JobSeekerNotificationsRouteImport } from './routes/job-seeker.notifications'
import { Route as JobSeekerDashboardRouteImport } from './routes/job-seeker.dashboard'
import { Route as EmployerSettingsRouteImport } from './routes/employer.settings'
import { Route as EmployerProfileRouteImport } from './routes/employer.profile'
import { Route as EmployerPendingApprovalRouteImport } from './routes/employer.pending-approval'
import { Route as EmployerJobsRouteImport } from './routes/employer.jobs'
import { Route as EmployerDashboardRouteImport } from './routes/employer.dashboard'
import { Route as EmployerApplicationsRouteImport } from './routes/employer.applications'
import { Route as AdminWorkforceRouteImport } from './routes/admin.workforce'
import { Route as AdminVerificationRouteImport } from './routes/admin.verification'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as RoleDashboardRouteImport } from './routes/$role.dashboard'
import { Route as WorkforceWorkersWorkerIdRouteImport } from './routes/workforce.workers.$workerId'
import { Route as MentorshipSessionsSessionIdRouteImport } from './routes/mentorship.sessions.$sessionId'
import { Route as MentorshipMentorsMentorIdRouteImport } from './routes/mentorship.mentors.$mentorId'
import { Route as JobsJobIdApplyRouteImport } from './routes/jobs.$jobId.apply'
import { Route as EmployerWorkforceSuccessRouteImport } from './routes/employer.workforce.success'
import { Route as EmployerWorkforceRequestRouteImport } from './routes/employer.workforce.request'
import { Route as EmployerWorkforceRecommendedRouteImport } from './routes/employer.workforce.recommended'
import { Route as EmployerWorkforceConfirmRouteImport } from './routes/employer.workforce.confirm'
import { Route as EmployerJobsNewRouteImport } from './routes/employer.jobs.new'
import { Route as EmployerApplicationsCandidateIdRouteImport } from './routes/employer.applications.$candidateId'
import { Route as EmployerWorkforceWorkersWorkerIdRouteImport } from './routes/employer.workforce.workers.$workerId'
import { Route as EmployerJobsJobIdEditRouteImport } from './routes/employer.jobs.$jobId.edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ChoosePathRoute = ChoosePathRouteImport.update({
  id: '/choose-path',
  path: '/choose-path',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationSubmittedRoute = ApplicationSubmittedRouteImport.update({
  id: '/application-submitted',
  path: '/application-submitted',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkforceWorkersRoute = WorkforceWorkersRouteImport.update({
  id: '/workforce/workers',
  path: '/workforce/workers',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkforceRegisterRoute = WorkforceRegisterRouteImport.update({
  id: '/workforce/register',
  path: '/workforce/register',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkforceProfileRoute = WorkforceProfileRouteImport.update({
  id: '/workforce/profile',
  path: '/workforce/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkforceDocumentsRoute = WorkforceDocumentsRouteImport.update({
  id: '/workforce/documents',
  path: '/workforce/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkforceDashboardRoute = WorkforceDashboardRouteImport.update({
  id: '/workforce/dashboard',
  path: '/workforce/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkforceCategoriesRoute = WorkforceCategoriesRouteImport.update({
  id: '/workforce/categories',
  path: '/workforce/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkforceAssignmentsRoute = WorkforceAssignmentsRouteImport.update({
  id: '/workforce/assignments',
  path: '/workforce/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorshipSessionsRoute = MentorshipSessionsRouteImport.update({
  id: '/mentorship/sessions',
  path: '/mentorship/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorshipRequestRoute = MentorshipRequestRouteImport.update({
  id: '/mentorship/request',
  path: '/mentorship/request',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorshipProgramsRoute = MentorshipProgramsRouteImport.update({
  id: '/mentorship/programs',
  path: '/mentorship/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorshipProfileRoute = MentorshipProfileRouteImport.update({
  id: '/mentorship/profile',
  path: '/mentorship/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorshipNotificationsRoute = MentorshipNotificationsRouteImport.update({
  id: '/mentorship/notifications',
  path: '/mentorship/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorshipMessagesRoute = MentorshipMessagesRouteImport.update({
  id: '/mentorship/messages',
  path: '/mentorship/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorshipMentorsRoute = MentorshipMentorsRouteImport.update({
  id: '/mentorship/mentors',
  path: '/mentorship/mentors',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorshipDashboardRoute = MentorshipDashboardRouteImport.update({
  id: '/mentorship/dashboard',
  path: '/mentorship/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => JobsRoute,
} as any)
const JobSeekerProfileRoute = JobSeekerProfileRouteImport.update({
  id: '/job-seeker/profile',
  path: '/job-seeker/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const JobSeekerNotificationsRoute = JobSeekerNotificationsRouteImport.update({
  id: '/job-seeker/notifications',
  path: '/job-seeker/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const JobSeekerDashboardRoute = JobSeekerDashboardRouteImport.update({
  id: '/job-seeker/dashboard',
  path: '/job-seeker/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerSettingsRoute = EmployerSettingsRouteImport.update({
  id: '/employer/settings',
  path: '/employer/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerProfileRoute = EmployerProfileRouteImport.update({
  id: '/employer/profile',
  path: '/employer/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerPendingApprovalRoute = EmployerPendingApprovalRouteImport.update({
  id: '/employer/pending-approval',
  path: '/employer/pending-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerJobsRoute = EmployerJobsRouteImport.update({
  id: '/employer/jobs',
  path: '/employer/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerDashboardRoute = EmployerDashboardRouteImport.update({
  id: '/employer/dashboard',
  path: '/employer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerApplicationsRoute = EmployerApplicationsRouteImport.update({
  id: '/employer/applications',
  path: '/employer/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWorkforceRoute = AdminWorkforceRouteImport.update({
  id: '/admin/workforce',
  path: '/admin/workforce',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVerificationRoute = AdminVerificationRouteImport.update({
  id: '/admin/verification',
  path: '/admin/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/admin/audit-logs',
  path: '/admin/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleDashboardRoute = RoleDashboardRouteImport.update({
  id: '/$role/dashboard',
  path: '/$role/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkforceWorkersWorkerIdRoute =
  WorkforceWorkersWorkerIdRouteImport.update({
    id: '/$workerId',
    path: '/$workerId',
    getParentRoute: () => WorkforceWorkersRoute,
  } as any)
const MentorshipSessionsSessionIdRoute =
  MentorshipSessionsSessionIdRouteImport.update({
    id: '/$sessionId',
    path: '/$sessionId',
    getParentRoute: () => MentorshipSessionsRoute,
  } as any)
const MentorshipMentorsMentorIdRoute =
  MentorshipMentorsMentorIdRouteImport.update({
    id: '/$mentorId',
    path: '/$mentorId',
    getParentRoute: () => MentorshipMentorsRoute,
  } as any)
const JobsJobIdApplyRoute = JobsJobIdApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => JobsJobIdRoute,
} as any)
const EmployerWorkforceSuccessRoute =
  EmployerWorkforceSuccessRouteImport.update({
    id: '/employer/workforce/success',
    path: '/employer/workforce/success',
    getParentRoute: () => rootRouteImport,
  } as any)
const EmployerWorkforceRequestRoute =
  EmployerWorkforceRequestRouteImport.update({
    id: '/employer/workforce/request',
    path: '/employer/workforce/request',
    getParentRoute: () => rootRouteImport,
  } as any)
const EmployerWorkforceRecommendedRoute =
  EmployerWorkforceRecommendedRouteImport.update({
    id: '/employer/workforce/recommended',
    path: '/employer/workforce/recommended',
    getParentRoute: () => rootRouteImport,
  } as any)
const EmployerWorkforceConfirmRoute =
  EmployerWorkforceConfirmRouteImport.update({
    id: '/employer/workforce/confirm',
    path: '/employer/workforce/confirm',
    getParentRoute: () => rootRouteImport,
  } as any)
const EmployerJobsNewRoute = EmployerJobsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => EmployerJobsRoute,
} as any)
const EmployerApplicationsCandidateIdRoute =
  EmployerApplicationsCandidateIdRouteImport.update({
    id: '/$candidateId',
    path: '/$candidateId',
    getParentRoute: () => EmployerApplicationsRoute,
  } as any)
const EmployerWorkforceWorkersWorkerIdRoute =
  EmployerWorkforceWorkersWorkerIdRouteImport.update({
    id: '/employer/workforce/workers/$workerId',
    path: '/employer/workforce/workers/$workerId',
    getParentRoute: () => rootRouteImport,
  } as any)
const EmployerJobsJobIdEditRoute = EmployerJobsJobIdEditRouteImport.update({
  id: '/$jobId/edit',
  path: '/$jobId/edit',
  getParentRoute: () => EmployerJobsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/application-submitted': typeof ApplicationSubmittedRoute
  '/choose-path': typeof ChoosePathRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/$role/dashboard': typeof RoleDashboardRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/admin/workforce': typeof AdminWorkforceRoute
  '/employer/applications': typeof EmployerApplicationsRouteWithChildren
  '/employer/dashboard': typeof EmployerDashboardRoute
  '/employer/jobs': typeof EmployerJobsRouteWithChildren
  '/employer/pending-approval': typeof EmployerPendingApprovalRoute
  '/employer/profile': typeof EmployerProfileRoute
  '/employer/settings': typeof EmployerSettingsRoute
  '/job-seeker/dashboard': typeof JobSeekerDashboardRoute
  '/job-seeker/notifications': typeof JobSeekerNotificationsRoute
  '/job-seeker/profile': typeof JobSeekerProfileRoute
  '/jobs/$jobId': typeof JobsJobIdRouteWithChildren
  '/mentorship/dashboard': typeof MentorshipDashboardRoute
  '/mentorship/mentors': typeof MentorshipMentorsRouteWithChildren
  '/mentorship/messages': typeof MentorshipMessagesRoute
  '/mentorship/notifications': typeof MentorshipNotificationsRoute
  '/mentorship/profile': typeof MentorshipProfileRoute
  '/mentorship/programs': typeof MentorshipProgramsRoute
  '/mentorship/request': typeof MentorshipRequestRoute
  '/mentorship/sessions': typeof MentorshipSessionsRouteWithChildren
  '/workforce/assignments': typeof WorkforceAssignmentsRoute
  '/workforce/categories': typeof WorkforceCategoriesRoute
  '/workforce/dashboard': typeof WorkforceDashboardRoute
  '/workforce/documents': typeof WorkforceDocumentsRoute
  '/workforce/profile': typeof WorkforceProfileRoute
  '/workforce/register': typeof WorkforceRegisterRoute
  '/workforce/workers': typeof WorkforceWorkersRouteWithChildren
  '/employer/applications/$candidateId': typeof EmployerApplicationsCandidateIdRoute
  '/employer/jobs/new': typeof EmployerJobsNewRoute
  '/employer/workforce/confirm': typeof EmployerWorkforceConfirmRoute
  '/employer/workforce/recommended': typeof EmployerWorkforceRecommendedRoute
  '/employer/workforce/request': typeof EmployerWorkforceRequestRoute
  '/employer/workforce/success': typeof EmployerWorkforceSuccessRoute
  '/jobs/$jobId/apply': typeof JobsJobIdApplyRoute
  '/mentorship/mentors/$mentorId': typeof MentorshipMentorsMentorIdRoute
  '/mentorship/sessions/$sessionId': typeof MentorshipSessionsSessionIdRoute
  '/workforce/workers/$workerId': typeof WorkforceWorkersWorkerIdRoute
  '/employer/jobs/$jobId/edit': typeof EmployerJobsJobIdEditRoute
  '/employer/workforce/workers/$workerId': typeof EmployerWorkforceWorkersWorkerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/application-submitted': typeof ApplicationSubmittedRoute
  '/choose-path': typeof ChoosePathRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/$role/dashboard': typeof RoleDashboardRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/admin/workforce': typeof AdminWorkforceRoute
  '/employer/applications': typeof EmployerApplicationsRouteWithChildren
  '/employer/dashboard': typeof EmployerDashboardRoute
  '/employer/jobs': typeof EmployerJobsRouteWithChildren
  '/employer/pending-approval': typeof EmployerPendingApprovalRoute
  '/employer/profile': typeof EmployerProfileRoute
  '/employer/settings': typeof EmployerSettingsRoute
  '/job-seeker/dashboard': typeof JobSeekerDashboardRoute
  '/job-seeker/notifications': typeof JobSeekerNotificationsRoute
  '/job-seeker/profile': typeof JobSeekerProfileRoute
  '/jobs/$jobId': typeof JobsJobIdRouteWithChildren
  '/mentorship/dashboard': typeof MentorshipDashboardRoute
  '/mentorship/mentors': typeof MentorshipMentorsRouteWithChildren
  '/mentorship/messages': typeof MentorshipMessagesRoute
  '/mentorship/notifications': typeof MentorshipNotificationsRoute
  '/mentorship/profile': typeof MentorshipProfileRoute
  '/mentorship/programs': typeof MentorshipProgramsRoute
  '/mentorship/request': typeof MentorshipRequestRoute
  '/mentorship/sessions': typeof MentorshipSessionsRouteWithChildren
  '/workforce/assignments': typeof WorkforceAssignmentsRoute
  '/workforce/categories': typeof WorkforceCategoriesRoute
  '/workforce/dashboard': typeof WorkforceDashboardRoute
  '/workforce/documents': typeof WorkforceDocumentsRoute
  '/workforce/profile': typeof WorkforceProfileRoute
  '/workforce/register': typeof WorkforceRegisterRoute
  '/workforce/workers': typeof WorkforceWorkersRouteWithChildren
  '/employer/applications/$candidateId': typeof EmployerApplicationsCandidateIdRoute
  '/employer/jobs/new': typeof EmployerJobsNewRoute
  '/employer/workforce/confirm': typeof EmployerWorkforceConfirmRoute
  '/employer/workforce/recommended': typeof EmployerWorkforceRecommendedRoute
  '/employer/workforce/request': typeof EmployerWorkforceRequestRoute
  '/employer/workforce/success': typeof EmployerWorkforceSuccessRoute
  '/jobs/$jobId/apply': typeof JobsJobIdApplyRoute
  '/mentorship/mentors/$mentorId': typeof MentorshipMentorsMentorIdRoute
  '/mentorship/sessions/$sessionId': typeof MentorshipSessionsSessionIdRoute
  '/workforce/workers/$workerId': typeof WorkforceWorkersWorkerIdRoute
  '/employer/jobs/$jobId/edit': typeof EmployerJobsJobIdEditRoute
  '/employer/workforce/workers/$workerId': typeof EmployerWorkforceWorkersWorkerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/application-submitted': typeof ApplicationSubmittedRoute
  '/choose-path': typeof ChoosePathRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/$role/dashboard': typeof RoleDashboardRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/admin/workforce': typeof AdminWorkforceRoute
  '/employer/applications': typeof EmployerApplicationsRouteWithChildren
  '/employer/dashboard': typeof EmployerDashboardRoute
  '/employer/jobs': typeof EmployerJobsRouteWithChildren
  '/employer/pending-approval': typeof EmployerPendingApprovalRoute
  '/employer/profile': typeof EmployerProfileRoute
  '/employer/settings': typeof EmployerSettingsRoute
  '/job-seeker/dashboard': typeof JobSeekerDashboardRoute
  '/job-seeker/notifications': typeof JobSeekerNotificationsRoute
  '/job-seeker/profile': typeof JobSeekerProfileRoute
  '/jobs/$jobId': typeof JobsJobIdRouteWithChildren
  '/mentorship/dashboard': typeof MentorshipDashboardRoute
  '/mentorship/mentors': typeof MentorshipMentorsRouteWithChildren
  '/mentorship/messages': typeof MentorshipMessagesRoute
  '/mentorship/notifications': typeof MentorshipNotificationsRoute
  '/mentorship/profile': typeof MentorshipProfileRoute
  '/mentorship/programs': typeof MentorshipProgramsRoute
  '/mentorship/request': typeof MentorshipRequestRoute
  '/mentorship/sessions': typeof MentorshipSessionsRouteWithChildren
  '/workforce/assignments': typeof WorkforceAssignmentsRoute
  '/workforce/categories': typeof WorkforceCategoriesRoute
  '/workforce/dashboard': typeof WorkforceDashboardRoute
  '/workforce/documents': typeof WorkforceDocumentsRoute
  '/workforce/profile': typeof WorkforceProfileRoute
  '/workforce/register': typeof WorkforceRegisterRoute
  '/workforce/workers': typeof WorkforceWorkersRouteWithChildren
  '/employer/applications/$candidateId': typeof EmployerApplicationsCandidateIdRoute
  '/employer/jobs/new': typeof EmployerJobsNewRoute
  '/employer/workforce/confirm': typeof EmployerWorkforceConfirmRoute
  '/employer/workforce/recommended': typeof EmployerWorkforceRecommendedRoute
  '/employer/workforce/request': typeof EmployerWorkforceRequestRoute
  '/employer/workforce/success': typeof EmployerWorkforceSuccessRoute
  '/jobs/$jobId/apply': typeof JobsJobIdApplyRoute
  '/mentorship/mentors/$mentorId': typeof MentorshipMentorsMentorIdRoute
  '/mentorship/sessions/$sessionId': typeof MentorshipSessionsSessionIdRoute
  '/workforce/workers/$workerId': typeof WorkforceWorkersWorkerIdRoute
  '/employer/jobs/$jobId/edit': typeof EmployerJobsJobIdEditRoute
  '/employer/workforce/workers/$workerId': typeof EmployerWorkforceWorkersWorkerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/application-submitted'
    | '/choose-path'
    | '/jobs'
    | '/login'
    | '/notifications'
    | '/register'
    | '/$role/dashboard'
    | '/admin/analytics'
    | '/admin/audit-logs'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/verification'
    | '/admin/workforce'
    | '/employer/applications'
    | '/employer/dashboard'
    | '/employer/jobs'
    | '/employer/pending-approval'
    | '/employer/profile'
    | '/employer/settings'
    | '/job-seeker/dashboard'
    | '/job-seeker/notifications'
    | '/job-seeker/profile'
    | '/jobs/$jobId'
    | '/mentorship/dashboard'
    | '/mentorship/mentors'
    | '/mentorship/messages'
    | '/mentorship/notifications'
    | '/mentorship/profile'
    | '/mentorship/programs'
    | '/mentorship/request'
    | '/mentorship/sessions'
    | '/workforce/assignments'
    | '/workforce/categories'
    | '/workforce/dashboard'
    | '/workforce/documents'
    | '/workforce/profile'
    | '/workforce/register'
    | '/workforce/workers'
    | '/employer/applications/$candidateId'
    | '/employer/jobs/new'
    | '/employer/workforce/confirm'
    | '/employer/workforce/recommended'
    | '/employer/workforce/request'
    | '/employer/workforce/success'
    | '/jobs/$jobId/apply'
    | '/mentorship/mentors/$mentorId'
    | '/mentorship/sessions/$sessionId'
    | '/workforce/workers/$workerId'
    | '/employer/jobs/$jobId/edit'
    | '/employer/workforce/workers/$workerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/application-submitted'
    | '/choose-path'
    | '/jobs'
    | '/login'
    | '/notifications'
    | '/register'
    | '/$role/dashboard'
    | '/admin/analytics'
    | '/admin/audit-logs'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/verification'
    | '/admin/workforce'
    | '/employer/applications'
    | '/employer/dashboard'
    | '/employer/jobs'
    | '/employer/pending-approval'
    | '/employer/profile'
    | '/employer/settings'
    | '/job-seeker/dashboard'
    | '/job-seeker/notifications'
    | '/job-seeker/profile'
    | '/jobs/$jobId'
    | '/mentorship/dashboard'
    | '/mentorship/mentors'
    | '/mentorship/messages'
    | '/mentorship/notifications'
    | '/mentorship/profile'
    | '/mentorship/programs'
    | '/mentorship/request'
    | '/mentorship/sessions'
    | '/workforce/assignments'
    | '/workforce/categories'
    | '/workforce/dashboard'
    | '/workforce/documents'
    | '/workforce/profile'
    | '/workforce/register'
    | '/workforce/workers'
    | '/employer/applications/$candidateId'
    | '/employer/jobs/new'
    | '/employer/workforce/confirm'
    | '/employer/workforce/recommended'
    | '/employer/workforce/request'
    | '/employer/workforce/success'
    | '/jobs/$jobId/apply'
    | '/mentorship/mentors/$mentorId'
    | '/mentorship/sessions/$sessionId'
    | '/workforce/workers/$workerId'
    | '/employer/jobs/$jobId/edit'
    | '/employer/workforce/workers/$workerId'
  id:
    | '__root__'
    | '/'
    | '/application-submitted'
    | '/choose-path'
    | '/jobs'
    | '/login'
    | '/notifications'
    | '/register'
    | '/$role/dashboard'
    | '/admin/analytics'
    | '/admin/audit-logs'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/verification'
    | '/admin/workforce'
    | '/employer/applications'
    | '/employer/dashboard'
    | '/employer/jobs'
    | '/employer/pending-approval'
    | '/employer/profile'
    | '/employer/settings'
    | '/job-seeker/dashboard'
    | '/job-seeker/notifications'
    | '/job-seeker/profile'
    | '/jobs/$jobId'
    | '/mentorship/dashboard'
    | '/mentorship/mentors'
    | '/mentorship/messages'
    | '/mentorship/notifications'
    | '/mentorship/profile'
    | '/mentorship/programs'
    | '/mentorship/request'
    | '/mentorship/sessions'
    | '/workforce/assignments'
    | '/workforce/categories'
    | '/workforce/dashboard'
    | '/workforce/documents'
    | '/workforce/profile'
    | '/workforce/register'
    | '/workforce/workers'
    | '/employer/applications/$candidateId'
    | '/employer/jobs/new'
    | '/employer/workforce/confirm'
    | '/employer/workforce/recommended'
    | '/employer/workforce/request'
    | '/employer/workforce/success'
    | '/jobs/$jobId/apply'
    | '/mentorship/mentors/$mentorId'
    | '/mentorship/sessions/$sessionId'
    | '/workforce/workers/$workerId'
    | '/employer/jobs/$jobId/edit'
    | '/employer/workforce/workers/$workerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationSubmittedRoute: typeof ApplicationSubmittedRoute
  ChoosePathRoute: typeof ChoosePathRoute
  JobsRoute: typeof JobsRouteWithChildren
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  RegisterRoute: typeof RegisterRoute
  RoleDashboardRoute: typeof RoleDashboardRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVerificationRoute: typeof AdminVerificationRoute
  AdminWorkforceRoute: typeof AdminWorkforceRoute
  EmployerApplicationsRoute: typeof EmployerApplicationsRouteWithChildren
  EmployerDashboardRoute: typeof EmployerDashboardRoute
  EmployerJobsRoute: typeof EmployerJobsRouteWithChildren
  EmployerPendingApprovalRoute: typeof EmployerPendingApprovalRoute
  EmployerProfileRoute: typeof EmployerProfileRoute
  EmployerSettingsRoute: typeof EmployerSettingsRoute
  JobSeekerDashboardRoute: typeof JobSeekerDashboardRoute
  JobSeekerNotificationsRoute: typeof JobSeekerNotificationsRoute
  JobSeekerProfileRoute: typeof JobSeekerProfileRoute
  MentorshipDashboardRoute: typeof MentorshipDashboardRoute
  MentorshipMentorsRoute: typeof MentorshipMentorsRouteWithChildren
  MentorshipMessagesRoute: typeof MentorshipMessagesRoute
  MentorshipNotificationsRoute: typeof MentorshipNotificationsRoute
  MentorshipProfileRoute: typeof MentorshipProfileRoute
  MentorshipProgramsRoute: typeof MentorshipProgramsRoute
  MentorshipRequestRoute: typeof MentorshipRequestRoute
  MentorshipSessionsRoute: typeof MentorshipSessionsRouteWithChildren
  WorkforceAssignmentsRoute: typeof WorkforceAssignmentsRoute
  WorkforceCategoriesRoute: typeof WorkforceCategoriesRoute
  WorkforceDashboardRoute: typeof WorkforceDashboardRoute
  WorkforceDocumentsRoute: typeof WorkforceDocumentsRoute
  WorkforceProfileRoute: typeof WorkforceProfileRoute
  WorkforceRegisterRoute: typeof WorkforceRegisterRoute
  WorkforceWorkersRoute: typeof WorkforceWorkersRouteWithChildren
  EmployerWorkforceConfirmRoute: typeof EmployerWorkforceConfirmRoute
  EmployerWorkforceRecommendedRoute: typeof EmployerWorkforceRecommendedRoute
  EmployerWorkforceRequestRoute: typeof EmployerWorkforceRequestRoute
  EmployerWorkforceSuccessRoute: typeof EmployerWorkforceSuccessRoute
  EmployerWorkforceWorkersWorkerIdRoute: typeof EmployerWorkforceWorkersWorkerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/choose-path': {
      id: '/choose-path'
      path: '/choose-path'
      fullPath: '/choose-path'
      preLoaderRoute: typeof ChoosePathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application-submitted': {
      id: '/application-submitted'
      path: '/application-submitted'
      fullPath: '/application-submitted'
      preLoaderRoute: typeof ApplicationSubmittedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workforce/workers': {
      id: '/workforce/workers'
      path: '/workforce/workers'
      fullPath: '/workforce/workers'
      preLoaderRoute: typeof WorkforceWorkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workforce/register': {
      id: '/workforce/register'
      path: '/workforce/register'
      fullPath: '/workforce/register'
      preLoaderRoute: typeof WorkforceRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workforce/profile': {
      id: '/workforce/profile'
      path: '/workforce/profile'
      fullPath: '/workforce/profile'
      preLoaderRoute: typeof WorkforceProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workforce/documents': {
      id: '/workforce/documents'
      path: '/workforce/documents'
      fullPath: '/workforce/documents'
      preLoaderRoute: typeof WorkforceDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workforce/dashboard': {
      id: '/workforce/dashboard'
      path: '/workforce/dashboard'
      fullPath: '/workforce/dashboard'
      preLoaderRoute: typeof WorkforceDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workforce/categories': {
      id: '/workforce/categories'
      path: '/workforce/categories'
      fullPath: '/workforce/categories'
      preLoaderRoute: typeof WorkforceCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workforce/assignments': {
      id: '/workforce/assignments'
      path: '/workforce/assignments'
      fullPath: '/workforce/assignments'
      preLoaderRoute: typeof WorkforceAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorship/sessions': {
      id: '/mentorship/sessions'
      path: '/mentorship/sessions'
      fullPath: '/mentorship/sessions'
      preLoaderRoute: typeof MentorshipSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorship/request': {
      id: '/mentorship/request'
      path: '/mentorship/request'
      fullPath: '/mentorship/request'
      preLoaderRoute: typeof MentorshipRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorship/programs': {
      id: '/mentorship/programs'
      path: '/mentorship/programs'
      fullPath: '/mentorship/programs'
      preLoaderRoute: typeof MentorshipProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorship/profile': {
      id: '/mentorship/profile'
      path: '/mentorship/profile'
      fullPath: '/mentorship/profile'
      preLoaderRoute: typeof MentorshipProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorship/notifications': {
      id: '/mentorship/notifications'
      path: '/mentorship/notifications'
      fullPath: '/mentorship/notifications'
      preLoaderRoute: typeof MentorshipNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorship/messages': {
      id: '/mentorship/messages'
      path: '/mentorship/messages'
      fullPath: '/mentorship/messages'
      preLoaderRoute: typeof MentorshipMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorship/mentors': {
      id: '/mentorship/mentors'
      path: '/mentorship/mentors'
      fullPath: '/mentorship/mentors'
      preLoaderRoute: typeof MentorshipMentorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorship/dashboard': {
      id: '/mentorship/dashboard'
      path: '/mentorship/dashboard'
      fullPath: '/mentorship/dashboard'
      preLoaderRoute: typeof MentorshipDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof JobsRoute
    }
    '/job-seeker/profile': {
      id: '/job-seeker/profile'
      path: '/job-seeker/profile'
      fullPath: '/job-seeker/profile'
      preLoaderRoute: typeof JobSeekerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-seeker/notifications': {
      id: '/job-seeker/notifications'
      path: '/job-seeker/notifications'
      fullPath: '/job-seeker/notifications'
      preLoaderRoute: typeof JobSeekerNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-seeker/dashboard': {
      id: '/job-seeker/dashboard'
      path: '/job-seeker/dashboard'
      fullPath: '/job-seeker/dashboard'
      preLoaderRoute: typeof JobSeekerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/settings': {
      id: '/employer/settings'
      path: '/employer/settings'
      fullPath: '/employer/settings'
      preLoaderRoute: typeof EmployerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/profile': {
      id: '/employer/profile'
      path: '/employer/profile'
      fullPath: '/employer/profile'
      preLoaderRoute: typeof EmployerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/pending-approval': {
      id: '/employer/pending-approval'
      path: '/employer/pending-approval'
      fullPath: '/employer/pending-approval'
      preLoaderRoute: typeof EmployerPendingApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/jobs': {
      id: '/employer/jobs'
      path: '/employer/jobs'
      fullPath: '/employer/jobs'
      preLoaderRoute: typeof EmployerJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/dashboard': {
      id: '/employer/dashboard'
      path: '/employer/dashboard'
      fullPath: '/employer/dashboard'
      preLoaderRoute: typeof EmployerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/applications': {
      id: '/employer/applications'
      path: '/employer/applications'
      fullPath: '/employer/applications'
      preLoaderRoute: typeof EmployerApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/workforce': {
      id: '/admin/workforce'
      path: '/admin/workforce'
      fullPath: '/admin/workforce'
      preLoaderRoute: typeof AdminWorkforceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/verification': {
      id: '/admin/verification'
      path: '/admin/verification'
      fullPath: '/admin/verification'
      preLoaderRoute: typeof AdminVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$role/dashboard': {
      id: '/$role/dashboard'
      path: '/$role/dashboard'
      fullPath: '/$role/dashboard'
      preLoaderRoute: typeof RoleDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workforce/workers/$workerId': {
      id: '/workforce/workers/$workerId'
      path: '/$workerId'
      fullPath: '/workforce/workers/$workerId'
      preLoaderRoute: typeof WorkforceWorkersWorkerIdRouteImport
      parentRoute: typeof WorkforceWorkersRoute
    }
    '/mentorship/sessions/$sessionId': {
      id: '/mentorship/sessions/$sessionId'
      path: '/$sessionId'
      fullPath: '/mentorship/sessions/$sessionId'
      preLoaderRoute: typeof MentorshipSessionsSessionIdRouteImport
      parentRoute: typeof MentorshipSessionsRoute
    }
    '/mentorship/mentors/$mentorId': {
      id: '/mentorship/mentors/$mentorId'
      path: '/$mentorId'
      fullPath: '/mentorship/mentors/$mentorId'
      preLoaderRoute: typeof MentorshipMentorsMentorIdRouteImport
      parentRoute: typeof MentorshipMentorsRoute
    }
    '/jobs/$jobId/apply': {
      id: '/jobs/$jobId/apply'
      path: '/apply'
      fullPath: '/jobs/$jobId/apply'
      preLoaderRoute: typeof JobsJobIdApplyRouteImport
      parentRoute: typeof JobsJobIdRoute
    }
    '/employer/workforce/success': {
      id: '/employer/workforce/success'
      path: '/employer/workforce/success'
      fullPath: '/employer/workforce/success'
      preLoaderRoute: typeof EmployerWorkforceSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/workforce/request': {
      id: '/employer/workforce/request'
      path: '/employer/workforce/request'
      fullPath: '/employer/workforce/request'
      preLoaderRoute: typeof EmployerWorkforceRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/workforce/recommended': {
      id: '/employer/workforce/recommended'
      path: '/employer/workforce/recommended'
      fullPath: '/employer/workforce/recommended'
      preLoaderRoute: typeof EmployerWorkforceRecommendedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/workforce/confirm': {
      id: '/employer/workforce/confirm'
      path: '/employer/workforce/confirm'
      fullPath: '/employer/workforce/confirm'
      preLoaderRoute: typeof EmployerWorkforceConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/jobs/new': {
      id: '/employer/jobs/new'
      path: '/new'
      fullPath: '/employer/jobs/new'
      preLoaderRoute: typeof EmployerJobsNewRouteImport
      parentRoute: typeof EmployerJobsRoute
    }
    '/employer/applications/$candidateId': {
      id: '/employer/applications/$candidateId'
      path: '/$candidateId'
      fullPath: '/employer/applications/$candidateId'
      preLoaderRoute: typeof EmployerApplicationsCandidateIdRouteImport
      parentRoute: typeof EmployerApplicationsRoute
    }
    '/employer/workforce/workers/$workerId': {
      id: '/employer/workforce/workers/$workerId'
      path: '/employer/workforce/workers/$workerId'
      fullPath: '/employer/workforce/workers/$workerId'
      preLoaderRoute: typeof EmployerWorkforceWorkersWorkerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/jobs/$jobId/edit': {
      id: '/employer/jobs/$jobId/edit'
      path: '/$jobId/edit'
      fullPath: '/employer/jobs/$jobId/edit'
      preLoaderRoute: typeof EmployerJobsJobIdEditRouteImport
      parentRoute: typeof EmployerJobsRoute
    }
  }
}

interface JobsJobIdRouteChildren {
  JobsJobIdApplyRoute: typeof JobsJobIdApplyRoute
}

const JobsJobIdRouteChildren: JobsJobIdRouteChildren = {
  JobsJobIdApplyRoute: JobsJobIdApplyRoute,
}

const JobsJobIdRouteWithChildren = JobsJobIdRoute._addFileChildren(
  JobsJobIdRouteChildren,
)

interface JobsRouteChildren {
  JobsJobIdRoute: typeof JobsJobIdRouteWithChildren
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsJobIdRoute: JobsJobIdRouteWithChildren,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

interface EmployerApplicationsRouteChildren {
  EmployerApplicationsCandidateIdRoute: typeof EmployerApplicationsCandidateIdRoute
}

const EmployerApplicationsRouteChildren: EmployerApplicationsRouteChildren = {
  EmployerApplicationsCandidateIdRoute: EmployerApplicationsCandidateIdRoute,
}

const EmployerApplicationsRouteWithChildren =
  EmployerApplicationsRoute._addFileChildren(EmployerApplicationsRouteChildren)

interface EmployerJobsRouteChildren {
  EmployerJobsNewRoute: typeof EmployerJobsNewRoute
  EmployerJobsJobIdEditRoute: typeof EmployerJobsJobIdEditRoute
}

const EmployerJobsRouteChildren: EmployerJobsRouteChildren = {
  EmployerJobsNewRoute: EmployerJobsNewRoute,
  EmployerJobsJobIdEditRoute: EmployerJobsJobIdEditRoute,
}

const EmployerJobsRouteWithChildren = EmployerJobsRoute._addFileChildren(
  EmployerJobsRouteChildren,
)

interface MentorshipMentorsRouteChildren {
  MentorshipMentorsMentorIdRoute: typeof MentorshipMentorsMentorIdRoute
}

const MentorshipMentorsRouteChildren: MentorshipMentorsRouteChildren = {
  MentorshipMentorsMentorIdRoute: MentorshipMentorsMentorIdRoute,
}

const MentorshipMentorsRouteWithChildren =
  MentorshipMentorsRoute._addFileChildren(MentorshipMentorsRouteChildren)

interface MentorshipSessionsRouteChildren {
  MentorshipSessionsSessionIdRoute: typeof MentorshipSessionsSessionIdRoute
}

const MentorshipSessionsRouteChildren: MentorshipSessionsRouteChildren = {
  MentorshipSessionsSessionIdRoute: MentorshipSessionsSessionIdRoute,
}

const MentorshipSessionsRouteWithChildren =
  MentorshipSessionsRoute._addFileChildren(MentorshipSessionsRouteChildren)

interface WorkforceWorkersRouteChildren {
  WorkforceWorkersWorkerIdRoute: typeof WorkforceWorkersWorkerIdRoute
}

const WorkforceWorkersRouteChildren: WorkforceWorkersRouteChildren = {
  WorkforceWorkersWorkerIdRoute: WorkforceWorkersWorkerIdRoute,
}

const WorkforceWorkersRouteWithChildren =
  WorkforceWorkersRoute._addFileChildren(WorkforceWorkersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationSubmittedRoute: ApplicationSubmittedRoute,
  ChoosePathRoute: ChoosePathRoute,
  JobsRoute: JobsRouteWithChildren,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  RegisterRoute: RegisterRoute,
  RoleDashboardRoute: RoleDashboardRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVerificationRoute: AdminVerificationRoute,
  AdminWorkforceRoute: AdminWorkforceRoute,
  EmployerApplicationsRoute: EmployerApplicationsRouteWithChildren,
  EmployerDashboardRoute: EmployerDashboardRoute,
  EmployerJobsRoute: EmployerJobsRouteWithChildren,
  EmployerPendingApprovalRoute: EmployerPendingApprovalRoute,
  EmployerProfileRoute: EmployerProfileRoute,
  EmployerSettingsRoute: EmployerSettingsRoute,
  JobSeekerDashboardRoute: JobSeekerDashboardRoute,
  JobSeekerNotificationsRoute: JobSeekerNotificationsRoute,
  JobSeekerProfileRoute: JobSeekerProfileRoute,
  MentorshipDashboardRoute: MentorshipDashboardRoute,
  MentorshipMentorsRoute: MentorshipMentorsRouteWithChildren,
  MentorshipMessagesRoute: MentorshipMessagesRoute,
  MentorshipNotificationsRoute: MentorshipNotificationsRoute,
  MentorshipProfileRoute: MentorshipProfileRoute,
  MentorshipProgramsRoute: MentorshipProgramsRoute,
  MentorshipRequestRoute: MentorshipRequestRoute,
  MentorshipSessionsRoute: MentorshipSessionsRouteWithChildren,
  WorkforceAssignmentsRoute: WorkforceAssignmentsRoute,
  WorkforceCategoriesRoute: WorkforceCategoriesRoute,
  WorkforceDashboardRoute: WorkforceDashboardRoute,
  WorkforceDocumentsRoute: WorkforceDocumentsRoute,
  WorkforceProfileRoute: WorkforceProfileRoute,
  WorkforceRegisterRoute: WorkforceRegisterRoute,
  WorkforceWorkersRoute: WorkforceWorkersRouteWithChildren,
  EmployerWorkforceConfirmRoute: EmployerWorkforceConfirmRoute,
  EmployerWorkforceRecommendedRoute: EmployerWorkforceRecommendedRoute,
  EmployerWorkforceRequestRoute: EmployerWorkforceRequestRoute,
  EmployerWorkforceSuccessRoute: EmployerWorkforceSuccessRoute,
  EmployerWorkforceWorkersWorkerIdRoute: EmployerWorkforceWorkersWorkerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
