/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as ChoosePathRouteImport } from './routes/choose-path'
import { Route as ApplicationSubmittedRouteImport } from './routes/application-submitted'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as JobSeekerDashboardRouteImport } from './routes/job-seeker.dashboard'
import { Route as EmployerSettingsRouteImport } from './routes/employer.settings'
import { Route as EmployerProfileRouteImport } from './routes/employer.profile'
import { Route as EmployerJobsRouteImport } from './routes/employer.jobs'
import { Route as EmployerDashboardRouteImport } from './routes/employer.dashboard'
import { Route as EmployerApplicationsRouteImport } from './routes/employer.applications'
import { Route as RoleDashboardRouteImport } from './routes/$role.dashboard'
import { Route as JobsJobIdApplyRouteImport } from './routes/jobs.$jobId.apply'
import { Route as EmployerJobsNewRouteImport } from './routes/employer.jobs.new'
import { Route as EmployerApplicationsCandidateIdRouteImport } from './routes/employer.applications.$candidateId'
import { Route as EmployerJobsJobIdEditRouteImport } from './routes/employer.jobs.$jobId.edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ChoosePathRoute = ChoosePathRouteImport.update({
  id: '/choose-path',
  path: '/choose-path',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationSubmittedRoute = ApplicationSubmittedRouteImport.update({
  id: '/application-submitted',
  path: '/application-submitted',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => JobsRoute,
} as any)
const JobSeekerDashboardRoute = JobSeekerDashboardRouteImport.update({
  id: '/job-seeker/dashboard',
  path: '/job-seeker/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerSettingsRoute = EmployerSettingsRouteImport.update({
  id: '/employer/settings',
  path: '/employer/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerProfileRoute = EmployerProfileRouteImport.update({
  id: '/employer/profile',
  path: '/employer/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerJobsRoute = EmployerJobsRouteImport.update({
  id: '/employer/jobs',
  path: '/employer/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerDashboardRoute = EmployerDashboardRouteImport.update({
  id: '/employer/dashboard',
  path: '/employer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerApplicationsRoute = EmployerApplicationsRouteImport.update({
  id: '/employer/applications',
  path: '/employer/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleDashboardRoute = RoleDashboardRouteImport.update({
  id: '/$role/dashboard',
  path: '/$role/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdApplyRoute = JobsJobIdApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => JobsJobIdRoute,
} as any)
const EmployerJobsNewRoute = EmployerJobsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => EmployerJobsRoute,
} as any)
const EmployerApplicationsCandidateIdRoute =
  EmployerApplicationsCandidateIdRouteImport.update({
    id: '/$candidateId',
    path: '/$candidateId',
    getParentRoute: () => EmployerApplicationsRoute,
  } as any)
const EmployerJobsJobIdEditRoute = EmployerJobsJobIdEditRouteImport.update({
  id: '/$jobId/edit',
  path: '/$jobId/edit',
  getParentRoute: () => EmployerJobsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/application-submitted': typeof ApplicationSubmittedRoute
  '/choose-path': typeof ChoosePathRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/$role/dashboard': typeof RoleDashboardRoute
  '/employer/applications': typeof EmployerApplicationsRouteWithChildren
  '/employer/dashboard': typeof EmployerDashboardRoute
  '/employer/jobs': typeof EmployerJobsRouteWithChildren
  '/employer/profile': typeof EmployerProfileRoute
  '/employer/settings': typeof EmployerSettingsRoute
  '/job-seeker/dashboard': typeof JobSeekerDashboardRoute
  '/jobs/$jobId': typeof JobsJobIdRouteWithChildren
  '/employer/applications/$candidateId': typeof EmployerApplicationsCandidateIdRoute
  '/employer/jobs/new': typeof EmployerJobsNewRoute
  '/jobs/$jobId/apply': typeof JobsJobIdApplyRoute
  '/employer/jobs/$jobId/edit': typeof EmployerJobsJobIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/application-submitted': typeof ApplicationSubmittedRoute
  '/choose-path': typeof ChoosePathRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/$role/dashboard': typeof RoleDashboardRoute
  '/employer/applications': typeof EmployerApplicationsRouteWithChildren
  '/employer/dashboard': typeof EmployerDashboardRoute
  '/employer/jobs': typeof EmployerJobsRouteWithChildren
  '/employer/profile': typeof EmployerProfileRoute
  '/employer/settings': typeof EmployerSettingsRoute
  '/job-seeker/dashboard': typeof JobSeekerDashboardRoute
  '/jobs/$jobId': typeof JobsJobIdRouteWithChildren
  '/employer/applications/$candidateId': typeof EmployerApplicationsCandidateIdRoute
  '/employer/jobs/new': typeof EmployerJobsNewRoute
  '/jobs/$jobId/apply': typeof JobsJobIdApplyRoute
  '/employer/jobs/$jobId/edit': typeof EmployerJobsJobIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/application-submitted': typeof ApplicationSubmittedRoute
  '/choose-path': typeof ChoosePathRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/$role/dashboard': typeof RoleDashboardRoute
  '/employer/applications': typeof EmployerApplicationsRouteWithChildren
  '/employer/dashboard': typeof EmployerDashboardRoute
  '/employer/jobs': typeof EmployerJobsRouteWithChildren
  '/employer/profile': typeof EmployerProfileRoute
  '/employer/settings': typeof EmployerSettingsRoute
  '/job-seeker/dashboard': typeof JobSeekerDashboardRoute
  '/jobs/$jobId': typeof JobsJobIdRouteWithChildren
  '/employer/applications/$candidateId': typeof EmployerApplicationsCandidateIdRoute
  '/employer/jobs/new': typeof EmployerJobsNewRoute
  '/jobs/$jobId/apply': typeof JobsJobIdApplyRoute
  '/employer/jobs/$jobId/edit': typeof EmployerJobsJobIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/application-submitted'
    | '/choose-path'
    | '/jobs'
    | '/login'
    | '/register'
    | '/$role/dashboard'
    | '/employer/applications'
    | '/employer/dashboard'
    | '/employer/jobs'
    | '/employer/profile'
    | '/employer/settings'
    | '/job-seeker/dashboard'
    | '/jobs/$jobId'
    | '/employer/applications/$candidateId'
    | '/employer/jobs/new'
    | '/jobs/$jobId/apply'
    | '/employer/jobs/$jobId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/application-submitted'
    | '/choose-path'
    | '/jobs'
    | '/login'
    | '/register'
    | '/$role/dashboard'
    | '/employer/applications'
    | '/employer/dashboard'
    | '/employer/jobs'
    | '/employer/profile'
    | '/employer/settings'
    | '/job-seeker/dashboard'
    | '/jobs/$jobId'
    | '/employer/applications/$candidateId'
    | '/employer/jobs/new'
    | '/jobs/$jobId/apply'
    | '/employer/jobs/$jobId/edit'
  id:
    | '__root__'
    | '/'
    | '/application-submitted'
    | '/choose-path'
    | '/jobs'
    | '/login'
    | '/register'
    | '/$role/dashboard'
    | '/employer/applications'
    | '/employer/dashboard'
    | '/employer/jobs'
    | '/employer/profile'
    | '/employer/settings'
    | '/job-seeker/dashboard'
    | '/jobs/$jobId'
    | '/employer/applications/$candidateId'
    | '/employer/jobs/new'
    | '/jobs/$jobId/apply'
    | '/employer/jobs/$jobId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationSubmittedRoute: typeof ApplicationSubmittedRoute
  ChoosePathRoute: typeof ChoosePathRoute
  JobsRoute: typeof JobsRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  RoleDashboardRoute: typeof RoleDashboardRoute
  EmployerApplicationsRoute: typeof EmployerApplicationsRouteWithChildren
  EmployerDashboardRoute: typeof EmployerDashboardRoute
  EmployerJobsRoute: typeof EmployerJobsRouteWithChildren
  EmployerProfileRoute: typeof EmployerProfileRoute
  EmployerSettingsRoute: typeof EmployerSettingsRoute
  JobSeekerDashboardRoute: typeof JobSeekerDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/choose-path': {
      id: '/choose-path'
      path: '/choose-path'
      fullPath: '/choose-path'
      preLoaderRoute: typeof ChoosePathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application-submitted': {
      id: '/application-submitted'
      path: '/application-submitted'
      fullPath: '/application-submitted'
      preLoaderRoute: typeof ApplicationSubmittedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof JobsRoute
    }
    '/job-seeker/dashboard': {
      id: '/job-seeker/dashboard'
      path: '/job-seeker/dashboard'
      fullPath: '/job-seeker/dashboard'
      preLoaderRoute: typeof JobSeekerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/settings': {
      id: '/employer/settings'
      path: '/employer/settings'
      fullPath: '/employer/settings'
      preLoaderRoute: typeof EmployerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/profile': {
      id: '/employer/profile'
      path: '/employer/profile'
      fullPath: '/employer/profile'
      preLoaderRoute: typeof EmployerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/jobs': {
      id: '/employer/jobs'
      path: '/employer/jobs'
      fullPath: '/employer/jobs'
      preLoaderRoute: typeof EmployerJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/dashboard': {
      id: '/employer/dashboard'
      path: '/employer/dashboard'
      fullPath: '/employer/dashboard'
      preLoaderRoute: typeof EmployerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/applications': {
      id: '/employer/applications'
      path: '/employer/applications'
      fullPath: '/employer/applications'
      preLoaderRoute: typeof EmployerApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$role/dashboard': {
      id: '/$role/dashboard'
      path: '/$role/dashboard'
      fullPath: '/$role/dashboard'
      preLoaderRoute: typeof RoleDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId/apply': {
      id: '/jobs/$jobId/apply'
      path: '/apply'
      fullPath: '/jobs/$jobId/apply'
      preLoaderRoute: typeof JobsJobIdApplyRouteImport
      parentRoute: typeof JobsJobIdRoute
    }
    '/employer/jobs/new': {
      id: '/employer/jobs/new'
      path: '/new'
      fullPath: '/employer/jobs/new'
      preLoaderRoute: typeof EmployerJobsNewRouteImport
      parentRoute: typeof EmployerJobsRoute
    }
    '/employer/applications/$candidateId': {
      id: '/employer/applications/$candidateId'
      path: '/$candidateId'
      fullPath: '/employer/applications/$candidateId'
      preLoaderRoute: typeof EmployerApplicationsCandidateIdRouteImport
      parentRoute: typeof EmployerApplicationsRoute
    }
    '/employer/jobs/$jobId/edit': {
      id: '/employer/jobs/$jobId/edit'
      path: '/$jobId/edit'
      fullPath: '/employer/jobs/$jobId/edit'
      preLoaderRoute: typeof EmployerJobsJobIdEditRouteImport
      parentRoute: typeof EmployerJobsRoute
    }
  }
}

interface JobsJobIdRouteChildren {
  JobsJobIdApplyRoute: typeof JobsJobIdApplyRoute
}

const JobsJobIdRouteChildren: JobsJobIdRouteChildren = {
  JobsJobIdApplyRoute: JobsJobIdApplyRoute,
}

const JobsJobIdRouteWithChildren = JobsJobIdRoute._addFileChildren(
  JobsJobIdRouteChildren,
)

interface JobsRouteChildren {
  JobsJobIdRoute: typeof JobsJobIdRouteWithChildren
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsJobIdRoute: JobsJobIdRouteWithChildren,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

interface EmployerApplicationsRouteChildren {
  EmployerApplicationsCandidateIdRoute: typeof EmployerApplicationsCandidateIdRoute
}

const EmployerApplicationsRouteChildren: EmployerApplicationsRouteChildren = {
  EmployerApplicationsCandidateIdRoute: EmployerApplicationsCandidateIdRoute,
}

const EmployerApplicationsRouteWithChildren =
  EmployerApplicationsRoute._addFileChildren(EmployerApplicationsRouteChildren)

interface EmployerJobsRouteChildren {
  EmployerJobsNewRoute: typeof EmployerJobsNewRoute
  EmployerJobsJobIdEditRoute: typeof EmployerJobsJobIdEditRoute
}

const EmployerJobsRouteChildren: EmployerJobsRouteChildren = {
  EmployerJobsNewRoute: EmployerJobsNewRoute,
  EmployerJobsJobIdEditRoute: EmployerJobsJobIdEditRoute,
}

const EmployerJobsRouteWithChildren = EmployerJobsRoute._addFileChildren(
  EmployerJobsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationSubmittedRoute: ApplicationSubmittedRoute,
  ChoosePathRoute: ChoosePathRoute,
  JobsRoute: JobsRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  RoleDashboardRoute: RoleDashboardRoute,
  EmployerApplicationsRoute: EmployerApplicationsRouteWithChildren,
  EmployerDashboardRoute: EmployerDashboardRoute,
  EmployerJobsRoute: EmployerJobsRouteWithChildren,
  EmployerProfileRoute: EmployerProfileRoute,
  EmployerSettingsRoute: EmployerSettingsRoute,
  JobSeekerDashboardRoute: JobSeekerDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
